export const types = {
    PRELOADER_ON: 'PRELOADER_ON',
    PRELOADER_OFF: 'PRELOADER_OFF',

    ALERT_ON: "ALERT_ON",
    ALERT_OFF: 'ALERT_OFF',
    USERS_LIST:'USERS_LIST',
    GET_USERS:'GET_USERS',
}